/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShipNavFlightMode from './ShipNavFlightMode';
import ShipNavRoute from './ShipNavRoute';
import ShipNavStatus from './ShipNavStatus';

/**
 * The ShipNav model module.
 * @module model/ShipNav
 * @version 2.0.0
 */
class ShipNav {
    /**
     * Constructs a new <code>ShipNav</code>.
     * The navigation information of the ship.
     * @alias module:model/ShipNav
     * @param systemSymbol {String} The system symbol of the ship's current location.
     * @param waypointSymbol {String} The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
     * @param route {module:model/ShipNavRoute} 
     * @param status {module:model/ShipNavStatus} 
     * @param flightMode {module:model/ShipNavFlightMode} 
     */
    constructor(systemSymbol, waypointSymbol, route, status, flightMode) { 
        
        ShipNav.initialize(this, systemSymbol, waypointSymbol, route, status, flightMode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, systemSymbol, waypointSymbol, route, status, flightMode) { 
        obj['systemSymbol'] = systemSymbol;
        obj['waypointSymbol'] = waypointSymbol;
        obj['route'] = route;
        obj['status'] = status;
        obj['flightMode'] = flightMode;
    }

    /**
     * Constructs a <code>ShipNav</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShipNav} obj Optional instance to populate.
     * @return {module:model/ShipNav} The populated <code>ShipNav</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShipNav();

            if (data.hasOwnProperty('systemSymbol')) {
                obj['systemSymbol'] = ApiClient.convertToType(data['systemSymbol'], 'String');
            }
            if (data.hasOwnProperty('waypointSymbol')) {
                obj['waypointSymbol'] = ApiClient.convertToType(data['waypointSymbol'], 'String');
            }
            if (data.hasOwnProperty('route')) {
                obj['route'] = ShipNavRoute.constructFromObject(data['route']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ShipNavStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('flightMode')) {
                obj['flightMode'] = ShipNavFlightMode.constructFromObject(data['flightMode']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShipNav</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShipNav</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ShipNav.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['systemSymbol'] && !(typeof data['systemSymbol'] === 'string' || data['systemSymbol'] instanceof String)) {
            throw new Error("Expected the field `systemSymbol` to be a primitive type in the JSON string but got " + data['systemSymbol']);
        }
        // ensure the json data is a string
        if (data['waypointSymbol'] && !(typeof data['waypointSymbol'] === 'string' || data['waypointSymbol'] instanceof String)) {
            throw new Error("Expected the field `waypointSymbol` to be a primitive type in the JSON string but got " + data['waypointSymbol']);
        }
        // validate the optional field `route`
        if (data['route']) { // data not null
          ShipNavRoute.validateJSON(data['route']);
        }

        return true;
    }


}

ShipNav.RequiredProperties = ["systemSymbol", "waypointSymbol", "route", "status", "flightMode"];

/**
 * The system symbol of the ship's current location.
 * @member {String} systemSymbol
 */
ShipNav.prototype['systemSymbol'] = undefined;

/**
 * The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
 * @member {String} waypointSymbol
 */
ShipNav.prototype['waypointSymbol'] = undefined;

/**
 * @member {module:model/ShipNavRoute} route
 */
ShipNav.prototype['route'] = undefined;

/**
 * @member {module:model/ShipNavStatus} status
 */
ShipNav.prototype['status'] = undefined;

/**
 * @member {module:model/ShipNavFlightMode} flightMode
 */
ShipNav.prototype['flightMode'] = undefined;






export default ShipNav;

