/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShipyardTransaction model module.
 * @module model/ShipyardTransaction
 * @version 2.0.0
 */
class ShipyardTransaction {
    /**
     * Constructs a new <code>ShipyardTransaction</code>.
     * @alias module:model/ShipyardTransaction
     * @param waypointSymbol {String} The symbol of the waypoint where the transaction took place.
     * @param shipSymbol {String} The symbol of the ship that was purchased.
     * @param price {Number} The price of the transaction.
     * @param agentSymbol {String} The symbol of the agent that made the transaction.
     * @param timestamp {Date} The timestamp of the transaction.
     */
    constructor(waypointSymbol, shipSymbol, price, agentSymbol, timestamp) { 
        
        ShipyardTransaction.initialize(this, waypointSymbol, shipSymbol, price, agentSymbol, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, waypointSymbol, shipSymbol, price, agentSymbol, timestamp) { 
        obj['waypointSymbol'] = waypointSymbol;
        obj['shipSymbol'] = shipSymbol;
        obj['price'] = price;
        obj['agentSymbol'] = agentSymbol;
        obj['timestamp'] = timestamp;
    }

    /**
     * Constructs a <code>ShipyardTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShipyardTransaction} obj Optional instance to populate.
     * @return {module:model/ShipyardTransaction} The populated <code>ShipyardTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShipyardTransaction();

            if (data.hasOwnProperty('waypointSymbol')) {
                obj['waypointSymbol'] = ApiClient.convertToType(data['waypointSymbol'], 'String');
            }
            if (data.hasOwnProperty('shipSymbol')) {
                obj['shipSymbol'] = ApiClient.convertToType(data['shipSymbol'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('agentSymbol')) {
                obj['agentSymbol'] = ApiClient.convertToType(data['agentSymbol'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShipyardTransaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShipyardTransaction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ShipyardTransaction.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['waypointSymbol'] && !(typeof data['waypointSymbol'] === 'string' || data['waypointSymbol'] instanceof String)) {
            throw new Error("Expected the field `waypointSymbol` to be a primitive type in the JSON string but got " + data['waypointSymbol']);
        }
        // ensure the json data is a string
        if (data['shipSymbol'] && !(typeof data['shipSymbol'] === 'string' || data['shipSymbol'] instanceof String)) {
            throw new Error("Expected the field `shipSymbol` to be a primitive type in the JSON string but got " + data['shipSymbol']);
        }
        // ensure the json data is a string
        if (data['agentSymbol'] && !(typeof data['agentSymbol'] === 'string' || data['agentSymbol'] instanceof String)) {
            throw new Error("Expected the field `agentSymbol` to be a primitive type in the JSON string but got " + data['agentSymbol']);
        }

        return true;
    }


}

ShipyardTransaction.RequiredProperties = ["waypointSymbol", "shipSymbol", "price", "agentSymbol", "timestamp"];

/**
 * The symbol of the waypoint where the transaction took place.
 * @member {String} waypointSymbol
 */
ShipyardTransaction.prototype['waypointSymbol'] = undefined;

/**
 * The symbol of the ship that was purchased.
 * @member {String} shipSymbol
 */
ShipyardTransaction.prototype['shipSymbol'] = undefined;

/**
 * The price of the transaction.
 * @member {Number} price
 */
ShipyardTransaction.prototype['price'] = undefined;

/**
 * The symbol of the agent that made the transaction.
 * @member {String} agentSymbol
 */
ShipyardTransaction.prototype['agentSymbol'] = undefined;

/**
 * The timestamp of the transaction.
 * @member {Date} timestamp
 */
ShipyardTransaction.prototype['timestamp'] = undefined;






export default ShipyardTransaction;

