/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AcceptContract200Response from './model/AcceptContract200Response';
import AcceptContract200ResponseData from './model/AcceptContract200ResponseData';
import Agent from './model/Agent';
import Chart from './model/Chart';
import ConnectedSystem from './model/ConnectedSystem';
import Contract from './model/Contract';
import ContractDeliverGood from './model/ContractDeliverGood';
import ContractPayment from './model/ContractPayment';
import ContractTerms from './model/ContractTerms';
import Cooldown from './model/Cooldown';
import CreateChart201Response from './model/CreateChart201Response';
import CreateChart201ResponseData from './model/CreateChart201ResponseData';
import CreateShipShipScan201Response from './model/CreateShipShipScan201Response';
import CreateShipShipScan201ResponseData from './model/CreateShipShipScan201ResponseData';
import CreateShipSystemScan201Response from './model/CreateShipSystemScan201Response';
import CreateShipSystemScan201ResponseData from './model/CreateShipSystemScan201ResponseData';
import CreateShipWaypointScan201Response from './model/CreateShipWaypointScan201Response';
import CreateShipWaypointScan201ResponseData from './model/CreateShipWaypointScan201ResponseData';
import CreateSurvey201Response from './model/CreateSurvey201Response';
import CreateSurvey201ResponseData from './model/CreateSurvey201ResponseData';
import DeliverContract200Response from './model/DeliverContract200Response';
import DeliverContract200ResponseData from './model/DeliverContract200ResponseData';
import DeliverContractRequest from './model/DeliverContractRequest';
import DockShip200Response from './model/DockShip200Response';
import ExtractResources201Response from './model/ExtractResources201Response';
import ExtractResources201ResponseData from './model/ExtractResources201ResponseData';
import ExtractResourcesRequest from './model/ExtractResourcesRequest';
import Extraction from './model/Extraction';
import ExtractionYield from './model/ExtractionYield';
import Faction from './model/Faction';
import FactionTrait from './model/FactionTrait';
import FulfillContract200Response from './model/FulfillContract200Response';
import GetContract200Response from './model/GetContract200Response';
import GetContracts200Response from './model/GetContracts200Response';
import GetFaction200Response from './model/GetFaction200Response';
import GetFactions200Response from './model/GetFactions200Response';
import GetJumpGate200Response from './model/GetJumpGate200Response';
import GetMarket200Response from './model/GetMarket200Response';
import GetMyAgent200Response from './model/GetMyAgent200Response';
import GetMyShip200Response from './model/GetMyShip200Response';
import GetMyShipCargo200Response from './model/GetMyShipCargo200Response';
import GetMyShips200Response from './model/GetMyShips200Response';
import GetShipCooldown200Response from './model/GetShipCooldown200Response';
import GetShipNav200Response from './model/GetShipNav200Response';
import GetShipyard200Response from './model/GetShipyard200Response';
import GetSystem200Response from './model/GetSystem200Response';
import GetSystemWaypoints200Response from './model/GetSystemWaypoints200Response';
import GetSystems200Response from './model/GetSystems200Response';
import GetWaypoint200Response from './model/GetWaypoint200Response';
import Jettison200Response from './model/Jettison200Response';
import Jettison200ResponseData from './model/Jettison200ResponseData';
import JettisonRequest from './model/JettisonRequest';
import JumpGate from './model/JumpGate';
import JumpShip200Response from './model/JumpShip200Response';
import JumpShip200ResponseData from './model/JumpShip200ResponseData';
import JumpShipRequest from './model/JumpShipRequest';
import Market from './model/Market';
import MarketTradeGood from './model/MarketTradeGood';
import MarketTransaction from './model/MarketTransaction';
import Meta from './model/Meta';
import NavigateShip200Response from './model/NavigateShip200Response';
import NavigateShip200ResponseData from './model/NavigateShip200ResponseData';
import NavigateShipRequest from './model/NavigateShipRequest';
import OrbitShip200Response from './model/OrbitShip200Response';
import OrbitShip200ResponseData from './model/OrbitShip200ResponseData';
import PatchShipNavRequest from './model/PatchShipNavRequest';
import PurchaseCargo201Response from './model/PurchaseCargo201Response';
import PurchaseCargoRequest from './model/PurchaseCargoRequest';
import PurchaseShip201Response from './model/PurchaseShip201Response';
import PurchaseShip201ResponseData from './model/PurchaseShip201ResponseData';
import PurchaseShipRequest from './model/PurchaseShipRequest';
import RefuelShip200Response from './model/RefuelShip200Response';
import RefuelShip200ResponseData from './model/RefuelShip200ResponseData';
import Register201Response from './model/Register201Response';
import Register201ResponseData from './model/Register201ResponseData';
import RegisterRequest from './model/RegisterRequest';
import ScannedShip from './model/ScannedShip';
import ScannedShipEngine from './model/ScannedShipEngine';
import ScannedShipFrame from './model/ScannedShipFrame';
import ScannedShipMountsInner from './model/ScannedShipMountsInner';
import ScannedShipReactor from './model/ScannedShipReactor';
import ScannedSystem from './model/ScannedSystem';
import ScannedWaypoint from './model/ScannedWaypoint';
import SellCargo201Response from './model/SellCargo201Response';
import SellCargo201ResponseData from './model/SellCargo201ResponseData';
import SellCargoRequest from './model/SellCargoRequest';
import Ship from './model/Ship';
import ShipCargo from './model/ShipCargo';
import ShipCargoItem from './model/ShipCargoItem';
import ShipCrew from './model/ShipCrew';
import ShipEngine from './model/ShipEngine';
import ShipFrame from './model/ShipFrame';
import ShipFuel from './model/ShipFuel';
import ShipFuelConsumed from './model/ShipFuelConsumed';
import ShipModule from './model/ShipModule';
import ShipMount from './model/ShipMount';
import ShipNav from './model/ShipNav';
import ShipNavFlightMode from './model/ShipNavFlightMode';
import ShipNavRoute from './model/ShipNavRoute';
import ShipNavRouteWaypoint from './model/ShipNavRouteWaypoint';
import ShipNavStatus from './model/ShipNavStatus';
import ShipReactor from './model/ShipReactor';
import ShipRefine200Response from './model/ShipRefine200Response';
import ShipRefine200ResponseData from './model/ShipRefine200ResponseData';
import ShipRefine200ResponseDataProducedInner from './model/ShipRefine200ResponseDataProducedInner';
import ShipRefineRequest from './model/ShipRefineRequest';
import ShipRegistration from './model/ShipRegistration';
import ShipRequirements from './model/ShipRequirements';
import ShipRole from './model/ShipRole';
import ShipType from './model/ShipType';
import Shipyard from './model/Shipyard';
import ShipyardShip from './model/ShipyardShip';
import ShipyardShipTypesInner from './model/ShipyardShipTypesInner';
import ShipyardTransaction from './model/ShipyardTransaction';
import Survey from './model/Survey';
import SurveyDeposit from './model/SurveyDeposit';
import System from './model/System';
import SystemFaction from './model/SystemFaction';
import SystemType from './model/SystemType';
import SystemWaypoint from './model/SystemWaypoint';
import TradeGood from './model/TradeGood';
import TradeSymbol from './model/TradeSymbol';
import TransferCargo200Response from './model/TransferCargo200Response';
import TransferCargoRequest from './model/TransferCargoRequest';
import Waypoint from './model/Waypoint';
import WaypointFaction from './model/WaypointFaction';
import WaypointOrbital from './model/WaypointOrbital';
import WaypointTrait from './model/WaypointTrait';
import WaypointType from './model/WaypointType';
import AgentsApi from './api/AgentsApi';
import ContractsApi from './api/ContractsApi';
import DefaultApi from './api/DefaultApi';
import FactionsApi from './api/FactionsApi';
import FleetApi from './api/FleetApi';
import SystemsApi from './api/SystemsApi';


/**
* SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  &#x60;&#x60;&#x60;json http {   \&quot;method\&quot;: \&quot;GET\&quot;,   \&quot;url\&quot;: \&quot;https://api.spacetraders.io/v2\&quot;, } &#x60;&#x60;&#x60;  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SpaceTradersApi = require('index'); // See note below*.
* var xxxSvc = new SpaceTradersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SpaceTradersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SpaceTradersApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SpaceTradersApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AcceptContract200Response model constructor.
     * @property {module:model/AcceptContract200Response}
     */
    AcceptContract200Response,

    /**
     * The AcceptContract200ResponseData model constructor.
     * @property {module:model/AcceptContract200ResponseData}
     */
    AcceptContract200ResponseData,

    /**
     * The Agent model constructor.
     * @property {module:model/Agent}
     */
    Agent,

    /**
     * The Chart model constructor.
     * @property {module:model/Chart}
     */
    Chart,

    /**
     * The ConnectedSystem model constructor.
     * @property {module:model/ConnectedSystem}
     */
    ConnectedSystem,

    /**
     * The Contract model constructor.
     * @property {module:model/Contract}
     */
    Contract,

    /**
     * The ContractDeliverGood model constructor.
     * @property {module:model/ContractDeliverGood}
     */
    ContractDeliverGood,

    /**
     * The ContractPayment model constructor.
     * @property {module:model/ContractPayment}
     */
    ContractPayment,

    /**
     * The ContractTerms model constructor.
     * @property {module:model/ContractTerms}
     */
    ContractTerms,

    /**
     * The Cooldown model constructor.
     * @property {module:model/Cooldown}
     */
    Cooldown,

    /**
     * The CreateChart201Response model constructor.
     * @property {module:model/CreateChart201Response}
     */
    CreateChart201Response,

    /**
     * The CreateChart201ResponseData model constructor.
     * @property {module:model/CreateChart201ResponseData}
     */
    CreateChart201ResponseData,

    /**
     * The CreateShipShipScan201Response model constructor.
     * @property {module:model/CreateShipShipScan201Response}
     */
    CreateShipShipScan201Response,

    /**
     * The CreateShipShipScan201ResponseData model constructor.
     * @property {module:model/CreateShipShipScan201ResponseData}
     */
    CreateShipShipScan201ResponseData,

    /**
     * The CreateShipSystemScan201Response model constructor.
     * @property {module:model/CreateShipSystemScan201Response}
     */
    CreateShipSystemScan201Response,

    /**
     * The CreateShipSystemScan201ResponseData model constructor.
     * @property {module:model/CreateShipSystemScan201ResponseData}
     */
    CreateShipSystemScan201ResponseData,

    /**
     * The CreateShipWaypointScan201Response model constructor.
     * @property {module:model/CreateShipWaypointScan201Response}
     */
    CreateShipWaypointScan201Response,

    /**
     * The CreateShipWaypointScan201ResponseData model constructor.
     * @property {module:model/CreateShipWaypointScan201ResponseData}
     */
    CreateShipWaypointScan201ResponseData,

    /**
     * The CreateSurvey201Response model constructor.
     * @property {module:model/CreateSurvey201Response}
     */
    CreateSurvey201Response,

    /**
     * The CreateSurvey201ResponseData model constructor.
     * @property {module:model/CreateSurvey201ResponseData}
     */
    CreateSurvey201ResponseData,

    /**
     * The DeliverContract200Response model constructor.
     * @property {module:model/DeliverContract200Response}
     */
    DeliverContract200Response,

    /**
     * The DeliverContract200ResponseData model constructor.
     * @property {module:model/DeliverContract200ResponseData}
     */
    DeliverContract200ResponseData,

    /**
     * The DeliverContractRequest model constructor.
     * @property {module:model/DeliverContractRequest}
     */
    DeliverContractRequest,

    /**
     * The DockShip200Response model constructor.
     * @property {module:model/DockShip200Response}
     */
    DockShip200Response,

    /**
     * The ExtractResources201Response model constructor.
     * @property {module:model/ExtractResources201Response}
     */
    ExtractResources201Response,

    /**
     * The ExtractResources201ResponseData model constructor.
     * @property {module:model/ExtractResources201ResponseData}
     */
    ExtractResources201ResponseData,

    /**
     * The ExtractResourcesRequest model constructor.
     * @property {module:model/ExtractResourcesRequest}
     */
    ExtractResourcesRequest,

    /**
     * The Extraction model constructor.
     * @property {module:model/Extraction}
     */
    Extraction,

    /**
     * The ExtractionYield model constructor.
     * @property {module:model/ExtractionYield}
     */
    ExtractionYield,

    /**
     * The Faction model constructor.
     * @property {module:model/Faction}
     */
    Faction,

    /**
     * The FactionTrait model constructor.
     * @property {module:model/FactionTrait}
     */
    FactionTrait,

    /**
     * The FulfillContract200Response model constructor.
     * @property {module:model/FulfillContract200Response}
     */
    FulfillContract200Response,

    /**
     * The GetContract200Response model constructor.
     * @property {module:model/GetContract200Response}
     */
    GetContract200Response,

    /**
     * The GetContracts200Response model constructor.
     * @property {module:model/GetContracts200Response}
     */
    GetContracts200Response,

    /**
     * The GetFaction200Response model constructor.
     * @property {module:model/GetFaction200Response}
     */
    GetFaction200Response,

    /**
     * The GetFactions200Response model constructor.
     * @property {module:model/GetFactions200Response}
     */
    GetFactions200Response,

    /**
     * The GetJumpGate200Response model constructor.
     * @property {module:model/GetJumpGate200Response}
     */
    GetJumpGate200Response,

    /**
     * The GetMarket200Response model constructor.
     * @property {module:model/GetMarket200Response}
     */
    GetMarket200Response,

    /**
     * The GetMyAgent200Response model constructor.
     * @property {module:model/GetMyAgent200Response}
     */
    GetMyAgent200Response,

    /**
     * The GetMyShip200Response model constructor.
     * @property {module:model/GetMyShip200Response}
     */
    GetMyShip200Response,

    /**
     * The GetMyShipCargo200Response model constructor.
     * @property {module:model/GetMyShipCargo200Response}
     */
    GetMyShipCargo200Response,

    /**
     * The GetMyShips200Response model constructor.
     * @property {module:model/GetMyShips200Response}
     */
    GetMyShips200Response,

    /**
     * The GetShipCooldown200Response model constructor.
     * @property {module:model/GetShipCooldown200Response}
     */
    GetShipCooldown200Response,

    /**
     * The GetShipNav200Response model constructor.
     * @property {module:model/GetShipNav200Response}
     */
    GetShipNav200Response,

    /**
     * The GetShipyard200Response model constructor.
     * @property {module:model/GetShipyard200Response}
     */
    GetShipyard200Response,

    /**
     * The GetSystem200Response model constructor.
     * @property {module:model/GetSystem200Response}
     */
    GetSystem200Response,

    /**
     * The GetSystemWaypoints200Response model constructor.
     * @property {module:model/GetSystemWaypoints200Response}
     */
    GetSystemWaypoints200Response,

    /**
     * The GetSystems200Response model constructor.
     * @property {module:model/GetSystems200Response}
     */
    GetSystems200Response,

    /**
     * The GetWaypoint200Response model constructor.
     * @property {module:model/GetWaypoint200Response}
     */
    GetWaypoint200Response,

    /**
     * The Jettison200Response model constructor.
     * @property {module:model/Jettison200Response}
     */
    Jettison200Response,

    /**
     * The Jettison200ResponseData model constructor.
     * @property {module:model/Jettison200ResponseData}
     */
    Jettison200ResponseData,

    /**
     * The JettisonRequest model constructor.
     * @property {module:model/JettisonRequest}
     */
    JettisonRequest,

    /**
     * The JumpGate model constructor.
     * @property {module:model/JumpGate}
     */
    JumpGate,

    /**
     * The JumpShip200Response model constructor.
     * @property {module:model/JumpShip200Response}
     */
    JumpShip200Response,

    /**
     * The JumpShip200ResponseData model constructor.
     * @property {module:model/JumpShip200ResponseData}
     */
    JumpShip200ResponseData,

    /**
     * The JumpShipRequest model constructor.
     * @property {module:model/JumpShipRequest}
     */
    JumpShipRequest,

    /**
     * The Market model constructor.
     * @property {module:model/Market}
     */
    Market,

    /**
     * The MarketTradeGood model constructor.
     * @property {module:model/MarketTradeGood}
     */
    MarketTradeGood,

    /**
     * The MarketTransaction model constructor.
     * @property {module:model/MarketTransaction}
     */
    MarketTransaction,

    /**
     * The Meta model constructor.
     * @property {module:model/Meta}
     */
    Meta,

    /**
     * The NavigateShip200Response model constructor.
     * @property {module:model/NavigateShip200Response}
     */
    NavigateShip200Response,

    /**
     * The NavigateShip200ResponseData model constructor.
     * @property {module:model/NavigateShip200ResponseData}
     */
    NavigateShip200ResponseData,

    /**
     * The NavigateShipRequest model constructor.
     * @property {module:model/NavigateShipRequest}
     */
    NavigateShipRequest,

    /**
     * The OrbitShip200Response model constructor.
     * @property {module:model/OrbitShip200Response}
     */
    OrbitShip200Response,

    /**
     * The OrbitShip200ResponseData model constructor.
     * @property {module:model/OrbitShip200ResponseData}
     */
    OrbitShip200ResponseData,

    /**
     * The PatchShipNavRequest model constructor.
     * @property {module:model/PatchShipNavRequest}
     */
    PatchShipNavRequest,

    /**
     * The PurchaseCargo201Response model constructor.
     * @property {module:model/PurchaseCargo201Response}
     */
    PurchaseCargo201Response,

    /**
     * The PurchaseCargoRequest model constructor.
     * @property {module:model/PurchaseCargoRequest}
     */
    PurchaseCargoRequest,

    /**
     * The PurchaseShip201Response model constructor.
     * @property {module:model/PurchaseShip201Response}
     */
    PurchaseShip201Response,

    /**
     * The PurchaseShip201ResponseData model constructor.
     * @property {module:model/PurchaseShip201ResponseData}
     */
    PurchaseShip201ResponseData,

    /**
     * The PurchaseShipRequest model constructor.
     * @property {module:model/PurchaseShipRequest}
     */
    PurchaseShipRequest,

    /**
     * The RefuelShip200Response model constructor.
     * @property {module:model/RefuelShip200Response}
     */
    RefuelShip200Response,

    /**
     * The RefuelShip200ResponseData model constructor.
     * @property {module:model/RefuelShip200ResponseData}
     */
    RefuelShip200ResponseData,

    /**
     * The Register201Response model constructor.
     * @property {module:model/Register201Response}
     */
    Register201Response,

    /**
     * The Register201ResponseData model constructor.
     * @property {module:model/Register201ResponseData}
     */
    Register201ResponseData,

    /**
     * The RegisterRequest model constructor.
     * @property {module:model/RegisterRequest}
     */
    RegisterRequest,

    /**
     * The ScannedShip model constructor.
     * @property {module:model/ScannedShip}
     */
    ScannedShip,

    /**
     * The ScannedShipEngine model constructor.
     * @property {module:model/ScannedShipEngine}
     */
    ScannedShipEngine,

    /**
     * The ScannedShipFrame model constructor.
     * @property {module:model/ScannedShipFrame}
     */
    ScannedShipFrame,

    /**
     * The ScannedShipMountsInner model constructor.
     * @property {module:model/ScannedShipMountsInner}
     */
    ScannedShipMountsInner,

    /**
     * The ScannedShipReactor model constructor.
     * @property {module:model/ScannedShipReactor}
     */
    ScannedShipReactor,

    /**
     * The ScannedSystem model constructor.
     * @property {module:model/ScannedSystem}
     */
    ScannedSystem,

    /**
     * The ScannedWaypoint model constructor.
     * @property {module:model/ScannedWaypoint}
     */
    ScannedWaypoint,

    /**
     * The SellCargo201Response model constructor.
     * @property {module:model/SellCargo201Response}
     */
    SellCargo201Response,

    /**
     * The SellCargo201ResponseData model constructor.
     * @property {module:model/SellCargo201ResponseData}
     */
    SellCargo201ResponseData,

    /**
     * The SellCargoRequest model constructor.
     * @property {module:model/SellCargoRequest}
     */
    SellCargoRequest,

    /**
     * The Ship model constructor.
     * @property {module:model/Ship}
     */
    Ship,

    /**
     * The ShipCargo model constructor.
     * @property {module:model/ShipCargo}
     */
    ShipCargo,

    /**
     * The ShipCargoItem model constructor.
     * @property {module:model/ShipCargoItem}
     */
    ShipCargoItem,

    /**
     * The ShipCrew model constructor.
     * @property {module:model/ShipCrew}
     */
    ShipCrew,

    /**
     * The ShipEngine model constructor.
     * @property {module:model/ShipEngine}
     */
    ShipEngine,

    /**
     * The ShipFrame model constructor.
     * @property {module:model/ShipFrame}
     */
    ShipFrame,

    /**
     * The ShipFuel model constructor.
     * @property {module:model/ShipFuel}
     */
    ShipFuel,

    /**
     * The ShipFuelConsumed model constructor.
     * @property {module:model/ShipFuelConsumed}
     */
    ShipFuelConsumed,

    /**
     * The ShipModule model constructor.
     * @property {module:model/ShipModule}
     */
    ShipModule,

    /**
     * The ShipMount model constructor.
     * @property {module:model/ShipMount}
     */
    ShipMount,

    /**
     * The ShipNav model constructor.
     * @property {module:model/ShipNav}
     */
    ShipNav,

    /**
     * The ShipNavFlightMode model constructor.
     * @property {module:model/ShipNavFlightMode}
     */
    ShipNavFlightMode,

    /**
     * The ShipNavRoute model constructor.
     * @property {module:model/ShipNavRoute}
     */
    ShipNavRoute,

    /**
     * The ShipNavRouteWaypoint model constructor.
     * @property {module:model/ShipNavRouteWaypoint}
     */
    ShipNavRouteWaypoint,

    /**
     * The ShipNavStatus model constructor.
     * @property {module:model/ShipNavStatus}
     */
    ShipNavStatus,

    /**
     * The ShipReactor model constructor.
     * @property {module:model/ShipReactor}
     */
    ShipReactor,

    /**
     * The ShipRefine200Response model constructor.
     * @property {module:model/ShipRefine200Response}
     */
    ShipRefine200Response,

    /**
     * The ShipRefine200ResponseData model constructor.
     * @property {module:model/ShipRefine200ResponseData}
     */
    ShipRefine200ResponseData,

    /**
     * The ShipRefine200ResponseDataProducedInner model constructor.
     * @property {module:model/ShipRefine200ResponseDataProducedInner}
     */
    ShipRefine200ResponseDataProducedInner,

    /**
     * The ShipRefineRequest model constructor.
     * @property {module:model/ShipRefineRequest}
     */
    ShipRefineRequest,

    /**
     * The ShipRegistration model constructor.
     * @property {module:model/ShipRegistration}
     */
    ShipRegistration,

    /**
     * The ShipRequirements model constructor.
     * @property {module:model/ShipRequirements}
     */
    ShipRequirements,

    /**
     * The ShipRole model constructor.
     * @property {module:model/ShipRole}
     */
    ShipRole,

    /**
     * The ShipType model constructor.
     * @property {module:model/ShipType}
     */
    ShipType,

    /**
     * The Shipyard model constructor.
     * @property {module:model/Shipyard}
     */
    Shipyard,

    /**
     * The ShipyardShip model constructor.
     * @property {module:model/ShipyardShip}
     */
    ShipyardShip,

    /**
     * The ShipyardShipTypesInner model constructor.
     * @property {module:model/ShipyardShipTypesInner}
     */
    ShipyardShipTypesInner,

    /**
     * The ShipyardTransaction model constructor.
     * @property {module:model/ShipyardTransaction}
     */
    ShipyardTransaction,

    /**
     * The Survey model constructor.
     * @property {module:model/Survey}
     */
    Survey,

    /**
     * The SurveyDeposit model constructor.
     * @property {module:model/SurveyDeposit}
     */
    SurveyDeposit,

    /**
     * The System model constructor.
     * @property {module:model/System}
     */
    System,

    /**
     * The SystemFaction model constructor.
     * @property {module:model/SystemFaction}
     */
    SystemFaction,

    /**
     * The SystemType model constructor.
     * @property {module:model/SystemType}
     */
    SystemType,

    /**
     * The SystemWaypoint model constructor.
     * @property {module:model/SystemWaypoint}
     */
    SystemWaypoint,

    /**
     * The TradeGood model constructor.
     * @property {module:model/TradeGood}
     */
    TradeGood,

    /**
     * The TradeSymbol model constructor.
     * @property {module:model/TradeSymbol}
     */
    TradeSymbol,

    /**
     * The TransferCargo200Response model constructor.
     * @property {module:model/TransferCargo200Response}
     */
    TransferCargo200Response,

    /**
     * The TransferCargoRequest model constructor.
     * @property {module:model/TransferCargoRequest}
     */
    TransferCargoRequest,

    /**
     * The Waypoint model constructor.
     * @property {module:model/Waypoint}
     */
    Waypoint,

    /**
     * The WaypointFaction model constructor.
     * @property {module:model/WaypointFaction}
     */
    WaypointFaction,

    /**
     * The WaypointOrbital model constructor.
     * @property {module:model/WaypointOrbital}
     */
    WaypointOrbital,

    /**
     * The WaypointTrait model constructor.
     * @property {module:model/WaypointTrait}
     */
    WaypointTrait,

    /**
     * The WaypointType model constructor.
     * @property {module:model/WaypointType}
     */
    WaypointType,

    /**
    * The AgentsApi service constructor.
    * @property {module:api/AgentsApi}
    */
    AgentsApi,

    /**
    * The ContractsApi service constructor.
    * @property {module:api/ContractsApi}
    */
    ContractsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The FactionsApi service constructor.
    * @property {module:api/FactionsApi}
    */
    FactionsApi,

    /**
    * The FleetApi service constructor.
    * @property {module:api/FleetApi}
    */
    FleetApi,

    /**
    * The SystemsApi service constructor.
    * @property {module:api/SystemsApi}
    */
    SystemsApi
};
